version: '3.9'
services:
  pantry-tracker-db:
    image: postgres
    restart: always
    container_name: pantry-tracker-db
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
# postgresql://postgres:example@localhost:5435/postgres"
# postgresql://nicolas:123456@HOST:5432/portfolio-backend-db-1
# postgresql://nicas:nicas@localhost:5432/portfolio?schema=public

