version: '3.9'
services:
  portfolio:
    image: postgres
    restart: always
    container_name: portfolio
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
